# Generated by Django 5.2.7 on 2025-10-25 21:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[products.models.validate_positive])),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
